version: '3.8'
name: garden

services:
  frontend:
    restart: on-failure
    build:
      context: frontend
      target: development
    image: garden/frontend
    container_name: garden-frontend
    hostname: frontend
    ports:
      - 3444:3444
    volumes:
      - ./frontend/app:/app
      - frontendModulesVolume:/app/node_modules
    depends_on:
      - backend
    networks:
      - default

  backend:
    restart: on-failure
    build:
      context: backend
      target: development
    image: garden/backend
    container_name: garden-backend
    hostname: backend
    ports:
      - 3333:3333
    volumes:
      - ./backend/app:/app
      - backendModulesVolume:/app/node_modules
    networks:
      - default

networks:
  default:
    name: garden-network

volumes:
  frontendModulesVolume:
  backendModulesVolume:
